from __future__ import annotations

from math import pi
from typing import Iterable, Sequence

from .config import ADPConfig
from .geometry import Loop, close_loop, distance
from .planner import ToolPass


def emit_gcode(
    passes: Iterable[ToolPass],
    config: ADPConfig,
    model_name: str = "adp_model",
) -> str:
    lines = [
        "; generated by Adaptive Detail Printing (ADP) Slicer 0.1.0",
        f"; model: {model_name}",
        "; strategy: fine outer wall first, coarse backing wall after each coarse-height band",
        f"; fine: {config.fine_tool} nozzle={fmt(config.fine_nozzle_mm)}mm layer={fmt(config.fine_layer_height_mm)}mm",
        f"; coarse: {config.coarse_tool} nozzle={fmt(config.coarse_nozzle_mm)}mm layer={fmt(config.coarse_layer_height_mm)}mm",
        "G21 ; millimeters",
        "G90 ; absolute XY",
        "M83 ; relative extrusion",
    ]

    current_tool: str | None = None
    current_z: float | None = None

    for tool_pass in passes:
        if tool_pass.tool != current_tool:
            lines.append(f"{tool_pass.tool} ; select ADP {'fine' if tool_pass.kind == 'fine_outer_wall' else 'coarse'} tool")
            lines.append("G92 E0")
            current_tool = tool_pass.tool

        label = (
            "ADP_FINE_OUTER_WALL"
            if tool_pass.kind == "fine_outer_wall"
            else "ADP_COARSE_BACKING_WALL"
        )
        lines.append(
            f"; {label} band={tool_pass.band_index + 1} z={fmt(tool_pass.z_mm)} "
            f"nozzle={fmt(tool_pass.nozzle_mm)} line_width={fmt(tool_pass.line_width_mm)}"
        )
        if tool_pass.fine_layer_index is not None:
            lines.append(f"; ADP_FINE_LAYER index={tool_pass.fine_layer_index}")

        if current_z is None or abs(current_z - tool_pass.z_mm) > 1e-6:
            lines.append(
                f"G0 Z{fmt(tool_pass.z_mm)} F{fmt(config.travel_feedrate_mm_min)}"
            )
            current_z = tool_pass.z_mm

        for loop in tool_pass.loops:
            lines.extend(_emit_loop(loop, tool_pass, config))

    lines.extend(
        [
            "; ADP_END",
            "G92 E0",
        ]
    )
    return "\n".join(lines) + "\n"


def _emit_loop(loop: Sequence[tuple[float, float]], tool_pass: ToolPass, config: ADPConfig) -> list[str]:
    points = close_loop(loop)
    start = points[0]
    lines = [
        f"G0 X{fmt(start[0])} Y{fmt(start[1])} F{fmt(config.travel_feedrate_mm_min)}"
    ]
    for index in range(1, len(points)):
        previous = points[index - 1]
        current = points[index]
        extrusion = extrusion_for_segment(
            distance(previous, current),
            tool_pass.line_width_mm,
            tool_pass.layer_height_mm,
            config,
        )
        lines.append(
            f"G1 X{fmt(current[0])} Y{fmt(current[1])} "
            f"E{fmt(extrusion, places=5)} F{fmt(tool_pass.feedrate_mm_min)}"
        )
    return lines


def extrusion_for_segment(
    length_mm: float, line_width_mm: float, layer_height_mm: float, config: ADPConfig
) -> float:
    filament_area = pi * (config.filament_diameter_mm / 2.0) ** 2
    deposited_volume = length_mm * line_width_mm * layer_height_mm
    return (deposited_volume / filament_area) * config.flow_multiplier


def fmt(value: float, places: int = 3) -> str:
    text = f"{value:.{places}f}"
    return text.rstrip("0").rstrip(".") if "." in text else text
